import  { StaticImageData } from 'next/image';
import logo from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo1 from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo2 from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo3 from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo4 from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo5 from '../../../../../public/Home/Mcansey 100X100 L.png';
import logo6 from '../../../../../public/Home/Mcansey 100X100 L.png';


export interface Job {
  id: number;
  logo: StaticImageData;
  company: string;
  title: string;
  location: string;
  postedTime: string;
  salary: string;
  jobType: string;
  industry: string;
  experience: string;
  education: string;
  onSiteRemote: string;
  skills: string[];
  link?: string;
}

export const filterOptions = [
  { label: 'Industry', value: 'industry' },
  { label: 'Location', value: 'location' },
  { label: 'Salary', value: 'salary' },
  { label: 'Experience', value: 'experience' },
  { label: 'Education', value: 'education' },
];

export const jobs: Job[] = [
  {
    id: 1,
    logo: logo,
    company: "LinkedIn",
    title: "AEM Developer",
    location: "Mumbai, India",
    postedTime: "1 hour ago",
    salary: "10 Lakh - 20 Lakh",
    jobType: "Full-Time",
    industry: "Software",
    experience: "5-7 Y",
    education: "Graduate",
    onSiteRemote: "onsite",
    skills: [" Sling Servlets and JSP development", "Sling Models Services", "OSGi/FELIX","CMS development experience"," Java Content Repository (JCR)/CRX"],
      link: '/jobs/aem-developer'
  },
  {
    id: 2,
    logo: logo,
    company: "Adobe",
    title: "AEM Architect",
    location: "Mumbai, India",
    postedTime: "2 hours ago",
    salary: "15 Lakh - 25 Lakh",
    jobType: "Full-Time",
    industry: "Finance",
    experience: "10-15 Y",
    education: "Graduate",
    onSiteRemote: "remote",
    skills: ["AEM Architect"],
      link: '/jobs/aem-architect'
  },
  {
    id: 3,
    logo: logo1,
    company: "Google",
    title: "React Native Developer",
    location: "Mumbai, India",
    postedTime: "3 hours ago",
    salary: "7 Lakh - 12 Lakh",
    jobType: "Full-Time",
    industry: "Tech",
    experience: "5-7 Y",
    education: "Graduate",
    onSiteRemote: "onsite",
    skills: ["React Native", "Flux", "Redux", "REST APIs"],
      link: '/jobs/react-native-developer'
  },
  {
    id: 4,
    logo: logo2,
    company: "Amazon",
    title: "PHP Developer",
    location: "Mumbai, India",
    postedTime: "4 hours ago",
    salary: "7 Lakh - 12 Lakh",
    jobType: "Full-Time",
    industry: "E-commerce",
    experience: "5+ Y",
    education: "Post-Graduate",
    onSiteRemote: "remote",
    skills: ["PHP Framework Like Laravel,", "CodeIgnetor", "Azure", "webserver"],
      link: '/jobs/php-laravel'
  },
  {
    id: 5,
    logo: logo3,
    company: "Microsoft",
    title: "Node Js Developer",
    location: "Mumbai, India",
    postedTime: "5 hours ago",
    salary: "10 Lakh - 12 Lakh",
    jobType: "Part-Time",
    industry: "Software",
    experience: "5+ Y",
    education: "Graduate",
    onSiteRemote: "onsite",
    skills: ["ExpressJS", "Docker", "GruntJS", "web servers such as Nginx, Apache"],
      link: '/jobs/nodejs-developer'
  },
  {
    id: 6,
    logo: logo4,
    company: "Apple",
    title: "React.Js Developer",
    location: "Mumbai, India",
    postedTime: "6 hours ago",
    salary: "5 Lakh - 7 Lakh",
    jobType: "Full-Time",
    industry: "Tech",
    experience: "5+ Y",
    education: "Graduate",
    onSiteRemote: "onsite",
    skills: ["React.Js", "Flux", "Redux", "Flow","REST APIs"],
      link: '/jobs/reactjs-developer'
  },
  {
    id: 7,
    logo: logo5,
    company: "IBM",
    title: "UI/UX Designer",
    location: "Mumbai, India",
    postedTime: "7 hours ago",
    salary: "5 Lakh - 7 Lakh",
    jobType: "Full-Time",
    industry: "Tech",
    experience: "5+ Y",
    education: "Graduate",
    onSiteRemote: "remote",
    skills: ["Figma", "Photoshop" ],
      link: '/jobs/ui-ux-designer'
  },
  {
    id: 8,
    logo: logo6,
    company: "NVIDIA",
    title: "SEO Executive",
    location: "Mumbai, India",
    postedTime: "8 hours ago",
    salary: "3.5 Lakh - 5 Lakh",
    jobType: "Full-Time",
    industry: "Software",
    experience: "4+ Y",
    education: "Post-Graduate",
    onSiteRemote: "remote",
    skills: ["Onpage", "Offpage", "Technical"],
      link: '/jobs/seo'
  },
  // {
  //   id: 9,
  //   logo: logo7,
  //   company: "Twitter",
  //   title: "Content Moderator",
  //   location: "Paris, France",
  //   postedTime: "9 hours ago",
  //   salary: "12 Lakh - 18 Lakh",
  //   jobType: "Part-Time",
  //   industry: "Social Media",
  //   experience: "1-2 Y",
  //   education: "UnderGraduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Moderation", "Social Media", "Content Review"]
  // },
  // {
  //   id: 10,
  //   logo: logo,
  //   company: "Facebook",
  //   title: "Digital Marketer",
  //   location: "Dubai, UAE",
  //   postedTime: "10 hours ago",
  //   salary: "50 Lakh - 80 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Advertising",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["SEO", "PPC", "Google Ads", "Content Marketing"]
  // },
  // {
  //   id: 11,
  //   logo:logo1,
  //   company: "Tesla",
  //   title: "Mechanical Engineer",
  //   location: "Los Angeles, US",
  //   postedTime: "11 hours ago",
  //   salary: "11 Lakh - 13 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Automotive",
  //   experience: "5-10 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["SolidWorks", "AutoCAD", "Prototyping", "Testing"]
  // },
  // {
  //   id: 12,
  //   logo: logo2,
  //   company: "Spotify",
  //   title: "Sound Engineer",
  //   location: "Stockholm, Sweden",
  //   postedTime: "12 hours ago",
  //   salary: "20 Lakh - 30 Lakh",
  //   jobType: "Part-Time",
  //   industry: "Music",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["Audio Mixing", "Pro Tools", "Logic Pro", "Studio Setup"]
  // },
  // {
  //   id: 13,
  //   logo: logo3,
  //   company: "Slack",
  //   title: "Cloud Engineer",
  //   location: "Vancouver, Canada",
  //   postedTime: "13 hours ago",
  //   salary: "9 Lakh - 12 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["AWS", "Kubernetes", "Docker", "CI/CD"]
  // },
  // {
  //   id: 14,
  //   logo:logo4,
  //   company: "Salesforce",
  //   title: "CRM Consultant",
  //   location: "Mumbai, India",
  //   postedTime: "14 hours ago",
  //   salary: "25 Lakh - 35 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Finance",
  //   experience: "4-6 Y",
  //   education: "Post-Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["Salesforce", "CRM", "Business Development", "Marketing"]
  // },
  // {
  //   id: 15,
  //   logo: logo5,
  //   company: "Uber",
  //   title: "Operations Manager",
  //   location: "Singapore",
  //   postedTime: "15 hours ago",
  //   salary: "10 Lakh - 13 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Transport",
  //   experience: "5-8 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Operations Management", "Logistics", "Supply Chain"]
  // },
  // {
  //   id: 17,
  //   logo: logo6,
  //   company: "Airbnb",
  //   title: "Hospitality Manager",
  //   location: "Sydney, Australia",
  //   postedTime: "17 hours ago",
  //   salary: "7 Lakh - 9 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Hospitality",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Customer Service", "Property Management", "Event Coordination"]
  // },
  // {
  //   id: 18,
  //   logo: logo7,
  //   company: "Zoom",
  //   title: "Customer Support Specialist",
  //   location: "Amsterdam, Netherlands",
  //   postedTime: "18 hours ago",
  //   salary: "15 Lakh - 20 Lakh",
  //   jobType: "Part-Time",
  //   industry: "Tech",
  //   experience: "1-2 Y",
  //   education: "Undergraduate",
  //   onSiteRemote: "remote",
  //   skills: ["Customer Support", "Technical Troubleshooting", "Zendesk"]
  // },
  // {
  //   id: 19,
  //   logo: logo,
  //   company: "eBay",
  //   title: "E-commerce Specialist",
  //   location: "Los Angeles, US",
  //   postedTime: "19 hours ago",
  //   salary: "80 Lakh - 100 Lakh",
  //   jobType: "Full-Time",
  //   industry: "E-commerce",
  //   experience: "2-3 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["SEO", "Product Listings", "Sales Analytics"]
  // },
  // {
  //   id: 20,
  //   logo:logo1,
  //   company: "Netflix",
  //   title: "Content Strategist",
  //   location: "San Francisco, US",
  //   postedTime: "20 hours ago",
  //   salary: "14 Lakh - 16 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Entertainment",
  //   experience: "5-8 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Content Creation", "Brand Strategy", "Audience Development"]
  // },
  // {
  //   id: 21,
  //   logo: logo2,
  //   company: "Starbucks",
  //   title: "Supply Chain Manager",
  //   location: "Mumbai, India",
  //   postedTime: "21 hours ago",
  //   salary: "20 Lakh - 30 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Retail",
  //   experience: "6-10 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["Supply Chain Optimization", "Vendor Management", "Logistics"]
  // },
  // {
  //   id: 22,
  //   logo: logo3,
  //   company: "Ford",
  //   title: "Automotive Engineer",
  //   location: "Detroit, US",
  //   postedTime: "22 hours ago",
  //   salary: "9 Lakh - 12 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Automotive",
  //   experience: "5-7 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["CAD", "Vehicle Dynamics", "Testing", "Manufacturing"]
  // },
  // {
  //   id: 23,
  //   logo: logo4,
  //   company: "PepsiCo",
  //   title: "Marketing Analyst",
  //   location: "Chicago, US",
  //   postedTime: "23 hours ago",
  //   salary: "8 Lakh - 11 Lakh",
  //   jobType: "Full-Time",
  //   industry: "FMCG",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Market Research", "Data Analysis", "Consumer Insights"]
  // },
  // {
  //   id: 24,
  //   logo: logo5,
  //   company: "Nike",
  //   title: "Retail Manager",
  //   location: "Paris, France",
  //   postedTime: "1 day ago",
  //   salary: "20 Lakh - 25 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Retail",
  //   experience: "5-7 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Sales Management", "Inventory Control", "Team Leadership"]
  // },
  // {
  //   id: 25,
  //   logo: logo6,
  //   company: "Walmart",
  //   title: "Data Analyst",
  //   location: "Toronto, Canada",
  //   postedTime: "1 day ago",
  //   salary: "9 Lakh - 12 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Retail",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["SQL", "Tableau", "Power BI", "Data Visualization"]
  // },
  // {
  //   id: 26,
  //   logo: logo7,
  //   company: "Cisco",
  //   title: "Network Engineer",
  //   location: "Austin, US",
  //   postedTime: "1 day ago",
  //   salary: "10 Lakh - 13 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Telecom",
  //   experience: "5-8 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Network Architecture", "Firewall Management", "Routing & Switching"]
  // },
  // {
  //   id: 27,
  //   logo: logo,
  //   company: "BMW",
  //   title: "Automotive Designer",
  //   location: "Munich, Germany",
  //   postedTime: "1 day ago",
  //   salary: "30 Lakh - 40 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Automotive",
  //   experience: "4-7 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["3D Modeling", "Prototyping", "Concept Design"]
  // },
  // {
  //   id: 28,
  //   logo: logo1,
  //   company: "Sony",
  //   title: "Game Developer",
  //   location: "Los Angeles, US",
  //   postedTime: "1 day ago",
  //   salary: "11 Lakh - 14 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Entertainment",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["C++", "Unity", "Game Physics", "AI"]
  // },
  // {
  //   id: 29,
  //   logo: logo2,
  //   company: "Dell",
  //   title: "Tech Support Engineer",
  //   location: "Bangalore, India",
  //   postedTime: "1 day ago",
  //   salary: "12 Lakh - 18 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "2-4 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Technical Support", "Windows Server", "Customer Service"]
  // },
  // {
  //   id: 30,
  //   logo: logo3,
  //   company: "Shell",
  //   title: "Petroleum Engineer",
  //   location: "Dubai, UAE",
  //   postedTime: "1 day ago",
  //   salary: "15 Lakh - 20 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Energy",
  //   experience: "5-10 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Reservoir Engineering", "Drilling", "Oil Exploration"]
  // },
  // {
  //   id: 31,
  //   logo: logo4,
  //   company: "Samsung",
  //   title: "Hardware Engineer",
  //   location: "Seoul, South Korea",
  //   postedTime: "1 day ago",
  //   salary: "25 Lakh - 35 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["PCB Design", "Semiconductor Fabrication", "Hardware Testing"]
  // },
  // {
  //   id: 32,
  //   logo: logo5,
  //   company: "Pinterest",
  //   title: "Graphic Designer",
  //   location: "Toronto, Canada",
  //   postedTime: "2 days ago",
  //   salary: "60 Lakh - 80 Lakh",
  //   jobType: "Part-Time",
  //   industry: "Tech",
  //   experience: "2-4 Y",
  //   education: "Undergraduate",
  //   onSiteRemote: "remote",
  //   skills: ["Photoshop", "Illustrator", "Typography"]
  // },
  // {
  //   id: 33,
  //   logo: logo6,
  //   company: "Oracle",
  //   title: "Database Administrator",
  //   location: "Singapore",
  //   postedTime: "2 days ago",
  //   salary: "11 Lakh - 14 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "4-6 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Oracle DB", "SQL", "Backup & Recovery", "Performance Tuning"]
  // },
  // {
  //   id: 34,
  //   logo: logo7,
  //   company: "TikTok",
  //   title: "Video Content Creator",
  //   location: "Los Angeles, US",
  //   postedTime: "2 days ago",
  //   salary: "7 Lakh - 9 Lakh",
  //   jobType: "Part-Time",
  //   industry: "Entertainment",
  //   experience: "1-3 Y",
  //   education: "Undergraduate",
  //   onSiteRemote: "remote",
  //   skills: ["Video Editing", "Content Creation", "Social Media Strategy"]
  // },
  // {
  //   id: 35,
  //   logo:logo,
  //   company: "Intel",
  //   title: "Software Engineer",
  //   location: "Austin, US",
  //   postedTime: "2 days ago",
  //   salary: "12 Lakh - 15 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "3-6 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["C++", "Embedded Systems", "Linux"]
  // },
  // {
  //   id: 36,
  //   logo: logo1,
  //   company: "L'Oréal",
  //   title: "Brand Manager",
  //   location: "Paris, France",
  //   postedTime: "2 days ago",
  //   salary: "10 Lakh - 13 Lakh",
  //   jobType: "Full-Time",
  //   industry: "FMCG",
  //   experience: "5-8 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Brand Strategy", "Marketing", "Product Launches"]
  // },
  // {
  //   id: 37,
  //   logo: logo2,
  //   company: "Boeing",
  //   title: "Aerospace Engineer",
  //   location: "Seattle, US",
  //   postedTime: "2 days ago",
  //   salary: "14 Lakh - 18 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Aerospace",
  //   experience: "6-9 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Flight Dynamics", "Simulation", "Systems Engineering"]
  // },
  // {
  //   id: 38,
  //   logo: logo3,
  //   company: "Disney",
  //   title: "Animator",
  //   location: "Orlando, US",
  //   postedTime: "2 days ago",
  //   salary: "7 Lakh - 10 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Entertainment",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["2D Animation", "Character Design", "Storyboarding"]
  // },
  // {
  //   id: 39,
  //   logo: logo4,
  //   company: "Nestlé",
  //   title: "Food Scientist",
  //   location: "Zurich, Switzerland",
  //   postedTime: "2 days ago",
  //   salary: "11 Lakh - 14 Lakh",
  //   jobType: "Full-Time",
  //   industry: "FMCG",
  //   experience: "5-8 Y",
  //   education: "Post-Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Food Chemistry", "Product Development", "Quality Control"]
  // },
  // {
  //   id: 40,
  //   logo: logo5,
  //   company: "AT&T",
  //   title: "Telecom Engineer",
  //   location: "New York, US",
  //   postedTime: "2 days ago",
  //   salary: "9 Lakh - 12 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Telecom",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Network Design", "5G", "Signal Processing"]
  // },
  // {
  //   id: 41,
  //   logo: logo6,
  //   company: "HP",
  //   title: "DevOps Engineer",
  //   location: "Bangalore, India",
  //   postedTime: "2 days ago",
  //   salary: "18 Lakh - 22 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Kubernetes", "CI/CD", "Automation", "AWS"]
  // },
  // {
  //   id: 42,
  //   logo: logo7,
  //   company: "Adidas",
  //   title: "Product Designer",
  //   location: "Berlin, Germany",
  //   postedTime: "3 days ago",
  //   salary: "20 Lakh - 30 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Retail",
  //   experience: "4-6 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Design Thinking", "User Research", "Prototyping"]
  // },
  // {
  //   id: 43,
  //   logo: logo,
  //   company: "Chevron",
  //   title: "Chemical Engineer",
  //   location: "Houston, US",
  //   postedTime: "3 days ago",
  //   salary: "13 Lakh - 16 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Energy",
  //   experience: "6-9 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Process Engineering", "Refinery Operations", "Safety Protocols"]
  // },
  // {
  //   id: 44,
  //   logo: logo1,
  //   company: "Hilton",
  //   title: "Hotel Manager",
  //   location: "Dubai, UAE",
  //   postedTime: "3 days ago",
  //   salary: "10 Lakh - 13 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Hospitality",
  //   experience: "5-8 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Hotel Management", "Guest Services", "Budget Management"]
  // },
  // {
  //   id: 45,
  //   logo:logo2,
  //   company: "Johnson & Johnson",
  //   title: "Pharmaceutical Sales Rep",
  //   location: "New Delhi, India",
  //   postedTime: "3 days ago",
  //   salary: "15 Lakh - 22 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Healthcare",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Sales", "Product Knowledge", "Client Relationship Management"]
  // },
  // {
  //   id: 46,
  //   logo: logo1,
  //   company: "Tesla",
  //   title: "Battery Engineer",
  //   location: "Palo Alto, US",
  //   postedTime: "4 days ago",
  //   salary: "12 Lakh - 15 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Automotive",
  //   experience: "5-7 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Lithium-ion Batteries", "Energy Storage", "Material Science"]
  // },
  // {
  //   id: 47,
  //   logo: logo2,
  //   company: "Spotify",
  //   title: "Music Curator",
  //   location: "Stockholm, Sweden",
  //   postedTime: "4 days ago",
  //   salary: "6 Lakh - 8 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Entertainment",
  //   experience: "2-4 Y",
  //   education: "Undergraduate",
  //   onSiteRemote: "remote",
  //   skills: ["Music Selection", "Playlist Curation", "Trend Analysis"]
  // },
  // {
  //   id: 48,
  //   logo: logo3,
  //   company: "Uber",
  //   title: "Data Scientist",
  //   location: "San Francisco, US",
  //   postedTime: "4 days ago",
  //   salary: "14 Lakh - 17 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "4-6 Y",
  //   education: "Graduate",
  //   onSiteRemote: "remote",
  //   skills: ["Python", "Machine Learning", "Data Modeling"]
  // },
  // {
  //   id: 49,
  //   logo: logo4,
  //   company: "DHL",
  //   title: "Logistics Coordinator",
  //   location: "Berlin, Germany",
  //   postedTime: "4 days ago",
  //   salary: "15 Lakh - 20 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Logistics",
  //   experience: "3-5 Y",
  //   education: "Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Supply Chain Management", "Inventory Control", "Fleet Management"]
  // },
  // {
  //   id: 50,
  //   logo: logo5,
  //   company: "Twitter",
  //   title: "Social Media Strategist",
  //   location: "New York, US",
  //   postedTime: "4 days ago",
  //   salary: "8 Lakh - 10 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Tech",
  //   experience: "2-4 Y",
  //   education: "Undergraduate",
  //   onSiteRemote: "remote",
  //   skills: ["Content Strategy", "Engagement Analysis", "Campaign Management"]
  // },
  // {
  //   id: 51,
  //   logo: logo6,
  //   company: "Heineken",
  //   title: "Brewmaster",
  //   location: "Amsterdam, Netherlands",
  //   postedTime: "5 days ago",
  //   salary: "7 Lakh - 9 Lakh",
  //   jobType: "Full-Time",
  //   industry: "Food & Beverage",
  //   experience: "5-7 Y",
  //   education: "Post-Graduate",
  //   onSiteRemote: "onsite",
  //   skills: ["Brewing", "Quality Control", "Recipe Development"]
  // }
];

export const filters = {
  industries: [
    'Software', 'Finance', 'Recruiting', 'Management', 'Advertising',
    'Marketing', 'Healthcare', 'Education', 'Engineering', 'Retail',
    'Hospitality', 'Real Estate', 'Construction', 'Telecommunications',
    'Transportation', 'Information Technology', 'Consulting', 'Media',
    'Entertainment', 'Non-Profit', 'Pharmaceutical', 'E-commerce',
    'Cybersecurity', 'Insurance', 'Legal', 'Manufacturing',
    'Logistics', 'Utilities', 'Biotechnology', 'Startups', 
    'Aerospace', 'Agriculture', 'Food & Beverage', 'Fashion',
    'Gaming', 'Art & Design', 'Automotive', 'Data Science', 
    'Public Relations', 'HR & Recruitment', 'Social Media', 
    'Environmental Services', 'Mining', 'Government', 'Television',
    'Philanthropy', 'Digital Marketing', 'Travel', 'Sports'
  ],
  locations: [
    'New York', 'Mumbai",San Francisco', 'Berlin', 'Tokyo', 
    'Paris', 'Los Angeles', 'Toronto', 'Sydney', 'Singapore',
    'Boston', 'Chicago', 'Austin', 'Seattle', 'Amsterdam',
    'Dublin', 'Mumbai', 'Dubai', 'Hong Kong', 'Beijing',
    'São Paulo', 'Mexico City', 'Madrid', 'Rome', 'Istanbul',
    'Zurich', 'Vienna', 'Stockholm', 'Copenhagen', 'Helsinki',
    'Bangkok', 'Kuala Lumpur', 'Lagos', 'Cape Town', 'Buenos Aires',
    'Moscow', 'Tel Aviv', 'Jakarta', 'Rio de Janeiro', 'Manila',
    'Lisbon', 'Brussels', 'Warsaw', 'Oslo', 'Amsterdam',
    'Calgary', 'Edmonton', 'Montreal', 'Atlanta', 'Philadelphia',
    'Charlotte', 'Nashville', 'Pittsburgh', 'Phoenix', 'Kansas City'
  ],
  salaryRanges: [
    '0 Lakh - 20 Lakh', '20 Lakh - 40 Lakh', '40 Lakh - 60 Lakh', 
    '50 Lakh - 60 Lakh', '60 Lakh - 70 Lakh', '70 Lakh - 80 Lakh', 
    '80 Lakh - 90 Lakh', '90 Lakh - 100 Lakh', '100 Lakh - 200 Lakh', 
    '200 Lakh - 300 Lakh', '300 Lakh - 400 Lakh', '$ Not disclosed'
  ],
  jobType: [
    'Full-Time', 'Part-time', 'Contract', 'Temporary', 'Internship', 
    'Freelance', 'Volunteer', 'Remote', 'On-Site'
  ],
  ExperienceLevel: [
    'Entry-Level', '1-3 Y', '2-4 Y', '3-5 Y', '5-7 Y', 
    '7-10 Y', '10+ Y', 'Senior Level', 'Junior Level'
  ],
  onSiteRemote: [
    'Onsite', 'Remote', 'Hybrid', 'Flexible', 'Telecommute'
  ],
  Education: [
    'Undergraduate', 'Graduate', 'Postgraduate', 'MCA', 'B.Tech', 
    'M.Tech', 'PhD', 'Diploma', 'Certificate', 'Associate Degree',
    'High School', 'Vocational Training'
  ],
};